name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
      - name: Tag Docker Images
        run: |
          docker tag ${{ DOCKER_USERNAME }}/${{ github.event.repository.name }}_backend:latest ${{ DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          docker tag ${{ DOCKER_USERNAME }}/${{ github.event.repository.name }}_frontend:latest ${{ DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          docker tag ${{ DOCKER_USERNAME }}/${{ github.event.repository.name }}_database:latest ${{ DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
      - name: Push to DockerHub repository
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
